version: '3'

networks: 
    portfolio_network:
        driver: bridge

services: 
    jekyll:
      image: jekyll/jekyll:latest
      container_name: portfolio_jekyll
      restart: unless-stopped
      networks:
        - portfolio_network
      working_dir: /srv/jekyll
      ports: 
          - $HTTP_PORT:4000
      volumes:
        # Source
        - ./docs:/srv/jekyll
        # Bundle Cache
        - $BUNDLE_CACHE:/usr/local/bundle
        # Site Cache
        - $SITE_CACHE:/srv/jekyll/_site
        # Vendor Cache
        - $VENDOR_CACHE:/srv/jekyll/vendor
        # Gem Cache
        - $GEM_CACHE:/usr/gem
      # command: jekyll serve
      command: jekyll serve --watch --force_polling --verbose